### ISSUE TITLE
Endpoints needed for Field Book BrAPI V2

### ISSUE THREAD

**Issue by BrapiCoordinatorSelby** [Breeding-Insight/brapi#23]
I went through the list of endpoints used in Field Book BrAPI V1 and converted that to BrAPI V2. There might be more needed when doing the implementation, but this is a good place to start.

- GET /programs                                
- GET /trials                                  
- GET /studies                                 
- GET /observationunits    
- GET /variables                               
- POST /observations                              
- PUT /observations        
- POST /images                                  
- PUT /images/{imageDbId}                      
- PUT /images/{imageDbId}/imagecontent

Please let me know if these should be split into separate issues.

**Comment by timparsons** [comment]
Fixed in #25
