### ISSUE TITLE
ApiException code not being populated for errors

### ISSUE THREAD

**Issue by nickpalladino** [Breeding-Insight/brapi#32]
@BrapiCoordinatorSelby @chaneylc The handleResponse method in BrapiClient is not populating the code in the ApiException for all the cases with subclassed ApiExceptions. This is causing problems in Field Book since it relies on that code and it's always 0 in those cases. I think we could probably not use the subclassed exceptions and keep the last else. Thoughts?

https://github.com/Breeding-Insight/brapi/blob/5fc6a7aa36165657f423fa8776a4f78b85fdf24c/brapi-java-client/src/main/java/org/brapi/client/v2/BrAPIClient.java#L842-L875

**Comment by BrapiCoordinatorSelby** [comment]
oooooh I see, yea that can work.
Another solution is to set the appropriate codes in the Constructor of each subclassed exception. I don't know where all those subclass exceptions are being used throughout the code, so I would either edit their constructors to fix the problem everywhere, or delete the subclasses entirely to remove the problem everywhere.
Either is fine by me
