### ISSUE TITLE
Field Book : import traits (mapping between BrAPI dataType and Field Book format)

### ISSUE THREAD

**Issue by leetaei** [Breeding-Insight/brapi#54]
The root problem is in the file BrAPIScale.java (https://github.com/Breeding-Insight/brapi/blob/develop/brapi-java-model/src/main/java/org/brapi/v2/model/pheno/BrAPIScale.java)

When a system is using non-standard trait data types, the type value is ignored.

Option 1: Modify the BrAPIScale class line 35 and change `datatype` to a String

Option 2: Modify the BrAPIScale class lines 99-105. Modify the setter to store a string and enum value when possible. Add getter method to accommodate ( `getDataTypeStr()` )

Option 3: Modify the BrAPITraitDataType enum to include all Field Book data type options as acceptable values

**Comment by timparsons** [comment]
@leetaei Thanks for pointing this out! Looks like it was a misunderstanding of the spec during implementation in that the spec specifies a string, but also an enumerated list of dataTypes.  

@BrapiCoordinatorSelby what are your thoughts on updating the spec in some way to give more transparency to this type of scenario?  I personally find it confusing to say a property is of type `string`, but the documentation specifies a finite enum.

**Comment by timparsons** [comment]
Created BI-1728

**Comment by timparsons** [comment]
@BrapiCoordinatorSelby @leetaei I've been doing some more thinking on this issue, and more broadly, fields like this in the spec (defined as a `string`, but has an enum of values).  I'd like to discuss this further before applying a fix to the BrAPI Java Client.

For this particular field, when importing via BrAPI, Field Book is currently expecting a scale to be one of the `dataTypes` defined in the enum in the BrAPI spec.  If Field Book didn't do that, then I don't see how Field Book could reliably pull data via BrAPI from different servers.  On the other side, if servers don't convert the `dataType` defined in the spec, then they would have to produce data types that are defined by Field Book, and now those servers become closely coupled to Field Book.

In my opinion, I see good value in having spec-defined values for the `dataType` field (the same could be said for other fields throughout the spec).

**Comment by BrapiCoordinatorSelby** [comment]
I agree conceptually, with a couple of points. 
1) The BrAPI spec is slow to change, so making that complete list of spec defined values will take much much longer to resolve and fix this issue. Making `dataType` a simple string will help a ton in the short term. 
2) Right now, Field Book has 2 two checks for the value of `dataType`. First, in the "BrAPIScale.java" object when being populated from JSON, and second in "BrAPIServiceV2.java" when converting from a BrAPI object to a s Field Book DB object. 
If we make `dataType` a simple string "BrAPIScale.java", then Field Book has the freedom to control whether it accepts BrAPI specific data types, Field Book specific data types, both, or something else. When BrAPI eventually gets a more comprehensive list of data types, Field Book can begin supporting them without dropping support for systems still using FB specific data types.  The decoupling can eventually happen in the app logic layer, not the JSON parsing layer.
